import { ReduxProvider } from "./redux-provider";
import "./globals.css";
import Header from "./components/Header/Header";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";
import Copyright from "./components/Copyright/Copyright";

export const metadata = {
  title: "RAFCART",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ReduxProvider>
          <Header />
          <Navbar />
          {children}
          <Footer />
          <Copyright />
        </ReduxProvider>
      </body>
    </html>
  );
}
